source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HorizontalFloatingHeaderLayout_Example' do
  pod "HorizontalFloatingHeaderLayout", :path => "../"
end

target 'HorizontalFloatingHeaderLayout_Tests' do
  pod "HorizontalFloatingHeaderLayout", :path => "../"

  
end
